"""agregar catalogo de formas de pago y renombrar mercadopago a qr

Revision ID: 1885e0211ab4
Revises: d08bdf9b40d3
Create Date: 2026-08-06 02:22:29.444239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1885e0211ab4'
down_revision: Union[str, Sequence[str], None] = 'd08bdf9b40d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formas_pago_detalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('EFECTIVO', 'DEBITO', 'CREDITO', 'TRANSFERENCIA', 'QR', name='metodopago'), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('formas_pago_detalle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_formas_pago_detalle_id'), ['id'], unique=False)

    with op.batch_alter_table('ventas_pago', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forma_pago_detalle_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_ventas_pago_forma_pago_detalle', 'formas_pago_detalle', ['forma_pago_detalle_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas_pago', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ventas_pago_forma_pago_detalle', type_='foreignkey')
        batch_op.drop_column('forma_pago_detalle_id')

    with op.batch_alter_table('formas_pago_detalle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_formas_pago_detalle_id'))

    op.drop_table('formas_pago_detalle')
    # ### end Alembic commands ###
