"""agregar telefono a sucursales

Revision ID: 854b2a71eb9b
Revises: d2aff6bb0d8e
Create Date: 2026-07-30 22:32:26.362755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '854b2a71eb9b'
down_revision: Union[str, Sequence[str], None] = 'd2aff6bb0d8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sucursales', sa.Column('telefono', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sucursales', 'telefono')
    # ### end Alembic commands ###
