"""agregar movimientos de stock y conteos de inventario

Revision ID: d08bdf9b40d3
Revises: dee55c188bd8
Create Date: 2026-08-04 19:29:28.524936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd08bdf9b40d3'
down_revision: Union[str, Sequence[str], None] = 'dee55c188bd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conteos_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('notas', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conteos_inventario_id'), 'conteos_inventario', ['id'], unique=False)
    op.create_table('movimientos_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('COMPRA', 'VENTA', 'ANULACION', 'AJUSTE_MANUAL', 'CONTEO', name='tipomovimientostock'), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('saldo_posterior', sa.Integer(), nullable=False),
    sa.Column('referencia_id', sa.Integer(), nullable=True),
    sa.Column('notas', sa.String(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimientos_stock_id'), 'movimientos_stock', ['id'], unique=False)
    op.create_table('conteos_inventario_detalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conteo_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('stock_sistema', sa.Integer(), nullable=False),
    sa.Column('cantidad_contada', sa.Integer(), nullable=False),
    sa.Column('diferencia', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conteo_id'], ['conteos_inventario.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conteos_inventario_detalle_id'), 'conteos_inventario_detalle', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conteos_inventario_detalle_id'), table_name='conteos_inventario_detalle')
    op.drop_table('conteos_inventario_detalle')
    op.drop_index(op.f('ix_movimientos_stock_id'), table_name='movimientos_stock')
    op.drop_table('movimientos_stock')
    op.drop_index(op.f('ix_conteos_inventario_id'), table_name='conteos_inventario')
    op.drop_table('conteos_inventario')
    # ### end Alembic commands ###
