"""esquema inicial

Revision ID: d2aff6bb0d8e
Revises: 
Create Date: 2026-07-30 22:31:35.780375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2aff6bb0d8e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_categorias_id'), 'categorias', ['id'], unique=False)
    op.create_table('configuracion_fiscal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razon_social', sa.String(), nullable=True),
    sa.Column('regimen', sa.Enum('MONOTRIBUTO', 'RESPONSABLE_INSCRIPTO', name='regimenfiscal'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuracion_fiscal_id'), 'configuracion_fiscal', ['id'], unique=False)
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('cuit', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proveedores_id'), 'proveedores', ['id'], unique=False)
    op.create_table('sucursales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sucursales_id'), 'sucursales', ['id'], unique=False)
    op.create_table('compras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('numero_comprobante', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compras_id'), 'compras', ['id'], unique=False)
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('imagen_url', sa.String(), nullable=True),
    sa.Column('iva_porcentaje', sa.Float(), nullable=False),
    sa.Column('precio_venta', sa.Float(), nullable=False),
    sa.Column('costo_promedio', sa.Float(), nullable=False),
    sa.Column('stock_minimo', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productos_codigo'), 'productos', ['codigo'], unique=True)
    op.create_index(op.f('ix_productos_id'), 'productos', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('rol', sa.Enum('SERVIDOR', 'POS', name='rolusuario'), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.create_table('compras_detalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compra_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('bultos', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('costo_unitario_neto', sa.Float(), nullable=False),
    sa.Column('iva_compra_porcentaje', sa.Float(), nullable=False),
    sa.Column('costo_unitario_final', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['compra_id'], ['compras.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compras_detalle_id'), 'compras_detalle', ['id'], unique=False)
    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('producto_id', 'sucursal_id', name='uq_stock_producto_sucursal')
    )
    op.create_index(op.f('ix_stock_id'), 'stock', ['id'], unique=False)
    op.create_table('turnos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('ABIERTO', 'CERRADO', name='estadoturno'), nullable=False),
    sa.Column('fecha_apertura', sa.DateTime(), nullable=True),
    sa.Column('monto_apertura', sa.Float(), nullable=False),
    sa.Column('fecha_cierre', sa.DateTime(), nullable=True),
    sa.Column('monto_contado_cierre', sa.Float(), nullable=True),
    sa.Column('detalle_arqueo', sa.String(), nullable=True),
    sa.Column('monto_esperado_cierre', sa.Float(), nullable=True),
    sa.Column('diferencia', sa.Float(), nullable=True),
    sa.Column('notas_cierre', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turnos_id'), 'turnos', ['id'], unique=False)
    op.create_table('movimientos_caja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turno_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('INGRESO', 'EGRESO', name='tipomovimientocaja'), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('motivo', sa.String(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['turno_id'], ['turnos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimientos_caja_id'), 'movimientos_caja', ['id'], unique=False)
    op.create_table('ventas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.String(), nullable=True),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('turno_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('ACTIVA', 'ANULADA', name='estadoventa'), nullable=False),
    sa.Column('anulada_en', sa.DateTime(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('numero_comprobante', sa.String(), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('propina', sa.Float(), nullable=False),
    sa.Column('total_neto', sa.Float(), nullable=False),
    sa.Column('total_iva', sa.Float(), nullable=False),
    sa.Column('ganancia_total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.ForeignKeyConstraint(['turno_id'], ['turnos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ventas_id'), 'ventas', ['id'], unique=False)
    op.create_index(op.f('ix_ventas_id_cliente'), 'ventas', ['id_cliente'], unique=True)
    op.create_table('ventas_detalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario_venta', sa.Float(), nullable=False),
    sa.Column('precio_unitario_neto', sa.Float(), nullable=False),
    sa.Column('costo_unitario_momento', sa.Float(), nullable=False),
    sa.Column('ganancia_unitaria', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ventas_detalle_id'), 'ventas_detalle', ['id'], unique=False)
    op.create_table('ventas_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('metodo_pago', sa.Enum('EFECTIVO', 'DEBITO', 'CREDITO', 'TRANSFERENCIA', 'MERCADOPAGO', name='metodopago'), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ventas_pago_id'), 'ventas_pago', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ventas_pago_id'), table_name='ventas_pago')
    op.drop_table('ventas_pago')
    op.drop_index(op.f('ix_ventas_detalle_id'), table_name='ventas_detalle')
    op.drop_table('ventas_detalle')
    op.drop_index(op.f('ix_ventas_id_cliente'), table_name='ventas')
    op.drop_index(op.f('ix_ventas_id'), table_name='ventas')
    op.drop_table('ventas')
    op.drop_index(op.f('ix_movimientos_caja_id'), table_name='movimientos_caja')
    op.drop_table('movimientos_caja')
    op.drop_index(op.f('ix_turnos_id'), table_name='turnos')
    op.drop_table('turnos')
    op.drop_index(op.f('ix_stock_id'), table_name='stock')
    op.drop_table('stock')
    op.drop_index(op.f('ix_compras_detalle_id'), table_name='compras_detalle')
    op.drop_table('compras_detalle')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_productos_id'), table_name='productos')
    op.drop_index(op.f('ix_productos_codigo'), table_name='productos')
    op.drop_table('productos')
    op.drop_index(op.f('ix_compras_id'), table_name='compras')
    op.drop_table('compras')
    op.drop_index(op.f('ix_sucursales_id'), table_name='sucursales')
    op.drop_table('sucursales')
    op.drop_index(op.f('ix_proveedores_id'), table_name='proveedores')
    op.drop_table('proveedores')
    op.drop_index(op.f('ix_configuracion_fiscal_id'), table_name='configuracion_fiscal')
    op.drop_table('configuracion_fiscal')
    op.drop_index(op.f('ix_categorias_id'), table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###
