"""agregar notas a categorias

Revision ID: dee55c188bd8
Revises: 854b2a71eb9b
Create Date: 2026-07-30 22:33:16.799785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dee55c188bd8'
down_revision: Union[str, Sequence[str], None] = '854b2a71eb9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categorias', sa.Column('notas', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categorias', 'notas')
    # ### end Alembic commands ###
